apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: auto-test
  namespace: biz
  name: auto-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auto-test
        qcloud-app: auto-test
        log-type: java
    spec:
      nodeSelector:
        kubernetes.io/hostname: 10.1.5.10
      imagePullSecrets:
        - name: kuainiujinke-registry
      terminationGracePeriodSeconds: 45
      containers:
        - name: auto-test
          image: registry.kuainiujinke.com/cd_biz/auto-vue:v1.1
          imagePullPolicy: Always
          env:
            - name: aliyun.logs.auto-test
              value: /data/logs/grantTEST_VERSION/*.log
            - name: aliyun.logs.auto-test.format
              value: json
          volumeMounts:
          - mountPath: "/data/logs"
            name: logs
          args: ["sh", "/data/www/init.sh"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 1500Mi
      volumes:
      - name: logs
        hostPath:
          path: /data/logs
          type: Directory
